from parser.unn_request import main
from analytic.analyhtml import AnalyticHtml
awfafafafawfafwafwafwafawfafwafafafafwawawafawfafawfawfafawfafawfafwafafawfawfaffawfafwafawfawfawfa
cl = AnalyticHtml(sy)